### ISSUE TITLE
Attachments / multi line messages

### ISSUE THREAD

**Issue by erroneousboat** [erroneousboat/slack-term#10]
Create some sort of support for attachment / multi line messages. Now it's just and empty message and the sender will be rendered as "unknown".

**Comment by lamartire** [comment]
@erroneousboat this issue actual in 0.4.1 version too. Without attachments – this client is not so useful 😢

**Comment by erroneousboat** [comment]
@lamartire this is a very old issue and referenced certain integrations not showing enough information. I'm not sure what you're getting at specifically, but on the master branch there has been made a change that adds more information for files. (#179)

**Comment by lamartire** [comment]
@erroneousboat oh, thank you for fast response! 🙌 
I'm kalmed down now 🌈
