### ISSUE TITLE
Support slash commands

### ISSUE THREAD

**Issue by stevenklar** [erroneousboat/slack-term#101]
Is it possbile to implement these two features via the slack api?

* /msg some-user (Single Conversation)
* /msg some-user,some-other-user,andsomeone-else (Multi Group Conversation)

**Comment by erroneousboat** [comment]
Not yet possible because of: https://github.com/nlopes/slack/pull/176

**Comment by erroneousboat** [comment]
https://godoc.org/github.com/nlopes/slack#SlashCommand

**Comment by acaloiaro** [comment]
FYI nlopes/slack#176 was resolved by https://github.com/nlopes/slack/pull/395
