### ISSUE TITLE
What format release binaries are in ?

### ISSUE THREAD

**Issue by unoexperto** [erroneousboat/slack-term#104]
Sorry for dumb question but what is this https://github.com/erroneousboat/slack-term/releases/download/v0.3.2/slack-term-linux-amd64 file exactly ? It doesn't look like archive and it's not executable either.

**Comment by robjloranger** [comment]
Looks like it is a 64 bit Linux binary. To execute it you must first make it executable. From a terminal `chmod +x slack-term-linux-amd64`. Hope that helps.

**Comment by unoexperto** [comment]
Ah I know what it is. I copy-pasted recommended config file but didn't realize it has C-style comments. Thus I was getting following error

```
2018/03/02 20:03:07 invalid character '/' looking for beginning of object key string

```

**Comment by rishijavia** [comment]
hey @unoexperto i am having the same problem.

1. downloaded the executable
2. renamed it to `slack-term` 
3. gave permission to execute using `chmod +x` 
4. moved to `/usr/local/bin`

but it's still giving me `zsh: exec format error: slack-term`

**Comment by youmjww** [comment]
I have the same problem as @rishijavia .
Please help me.
