### ISSUE TITLE
Shared channels

### ISSUE THREAD

**Issue by Willamin** [erroneousboat/slack-term#106]
My Slack org has a few shared channels with other Slack orgs. These shared channels don't show up in the channel list in slack-term.

https://api.slack.com/shared-channels

**Comment by erroneousboat** [comment]
It seems the feature is in beta  (https://get.slack.help/hc/en-us/articles/115004151203-Create-shared-channels-on-a-workspace-beta-) and as such it doesn't seem [nlopes/slack](https://github.com/nlopes) supports it yet. Will revist this, when it does.

**Comment by antonipx** [comment]
It seems that there is a new "conversations" API that supports all channel types: https://api.slack.com/docs/conversations-api

**Comment by erroneousboat** [comment]
Present in v0.4.1 (https://github.com/erroneousboat/slack-term/issues/150)
