### ISSUE TITLE
Allow specifying a command to be run when events happen

### ISSUE THREAD

**Issue by nicklan** [erroneousboat/slack-term#109]
It would be great if I could specify in my config a command to run when things happen (like a new message coming in).

I don't think slack-term should try and get into the business of showing notifications, but I still want to get them.  This would allow me to use `notify-send` to handle this.  I'm sure there are lots of other use cases as well.

Thanks!

**Comment by erroneousboat** [comment]
I'm more inclined to add desktop notifications (#107) than supporting running commands. This in part because the next feature request will be to support commands to be run on specific kind of messages, I think other slack programs are better suited for that.
