### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Jamez312** [erroneousboat/slack-term#110]
I'm interested in beginning translating the project into Spanish and I was wondering if I could start pull requests of the files. Many thanks in advance!

**Comment by danielpa9708** [comment]
I'm interested as well

**Comment by erroneousboat** [comment]
Thank you for your offer, however I'm going to decline. This is because for future releases slack-term need to support those languages and the documentation will quickly become outdated for those languages if there are no translators for them.
