### ISSUE TITLE
invalid argument

### ISSUE THREAD

**Issue by googley** [erroneousboat/slack-term#113]
![screenshot_1](https://user-images.githubusercontent.com/2671317/37028744-6668cd6e-2135-11e8-8bf7-10d0cb6f0229.jpg)

* OS: `Linux laptop 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux` (Bash on Ubuntu on Windows)
* Install method: `go get`
* Terminal: `xterm`
* Configuration: Copy of the exemple in README, without other modification than the token.

**Comment by meain** [comment]
Remove the commented lines in the config

**Comment by googley** [comment]
Already done (but not specified, sorry)

**Comment by nickspoons** [comment]
I also get this error, also using WSL, although mine is a little different, I am running arch and installed slack-term from the aur - which just means that I git-pulled and built the binary.

The config file doesn't seem to have any effect - I get the same "<timestamp> invalid argument" error with or without a ~/slack-term.json

**Comment by erroneousboat** [comment]
Make sure your `slack-term.json` file is valid json. If done so and it still doesn't work post the json file here.

**Comment by scrossan-crown** [comment]
I'm having the exact same issues the only key in my slack-term.json is "slack_token" but it's still giving me invalid argument

**Comment by erroneousboat** [comment]
Could this be of help?

https://github.com/Microsoft/WSL/issues/69

**Comment by ocket8888** [comment]
FYI the workarounds for the linked WSL issues are to run the console as an administrator, as there can be a permissions error on the Windows side even when a process is run as root on the WSL side.

Don't know if that helps anyone, but for whatever it's worth, does not work for me.
