### ISSUE TITLE
Dependency management tool like dep can be used to manage dependencies

### ISSUE THREAD

**Issue by bharath-srinivas** [erroneousboat/slack-term#114]
Instead of pushing the entire vendor folder, some dependency management tool like [dep](https://github.com/golang/dep) can be used. This will reduce the overhead of pushing the vendor folder every time a new external library is used.

**Comment by erroneousboat** [comment]
Vendor folder is added to git because it makes it easier to build the project without dependency management tools. There are several reasons, for and against it, but I've chosen to add it to the project.

**Comment by pityonline** [comment]
In a slow network environment, it takes a very long time to complete the vendor directory. Especially in China mainland, usually, it's 10KiB/s. In my opinion, it's better to use dep to avoid repeated downloads.
