### ISSUE TITLE
Change the config file to be hidden

### ISSUE THREAD

**Issue by codyleyhan** [erroneousboat/slack-term#118]
I think it would be really good to have the config file be **.slack-term.json** instead so that it does not show up when you run ```ls``` and is much more common convention for config files for apps

**Comment by robjloranger** [comment]
I agree, I've just created an alias and have mine hidden

**Comment by dolanor** [comment]
Can I add to put it in the new "standard" way of managing configuration files by putting it in the `$XDG_CONFIG_HOME` (most of the time, it is `$HOME/.config`)
That would be even better :)
