### ISSUE TITLE
Can't seem to tag/notify other users

### ISSUE THREAD

**Issue by davealbert** [erroneousboat/slack-term#121]
First this is GREAT! I was so disappointed to see irc support being removed, this is better.

When I @tag someone (or a bot) it sends as text and doesn't notify (or execute the bot instruction).  Is there already somewhere else that's tracking this?  I didn't see an open issue for it.

**Comment by bharath-srinivas** [comment]
You have to enclose the `@username` within `<>` to tag someone. Try `<@user1>` and it'll work fine.

**Comment by davealbert** [comment]
Thanks @bharath-srinivas perfect.  Was that in the readme, sorry if I missed it.

**Comment by bharath-srinivas** [comment]
No it wasn't. You can find these things in [official documentation](https://api.slack.com/docs/message-formatting#how_to_escape_characters) of slack API.

**Comment by flyte** [comment]
Might be worth putting that link into the readme then. I had to search around in old, closed issues to find this information, and I wouldn't have thought to look at Slack's API docs.
