### ISSUE TITLE
Hide Multi-Person Direct Messages

### ISSUE THREAD

**Issue by nathanleach-corevist** [erroneousboat/slack-term#122]
Is (or can there be) a way to hide mpdm in the channel list? Although I've hidden them in the Ubuntu Slack client they all still show in slack-term.
![screenshot from 2018-03-16 11-15-27](https://user-images.githubusercontent.com/4182387/37528739-c1d3e71e-290b-11e8-92f0-e3bc60cd29dd.png)

**Comment by pomke** [comment]
100%, I'm trying this out for the first time and my channel list is a mile long..

**Comment by erroneousboat** [comment]
I think the current workaround is leaving/closing the channels from slack site itself. I'm looking into implementing slash commands that should make it possible to leave channels (#101), I prefer this than to implement a custom key for hiding/leaving/closing channels.

**Comment by daved** [comment]
> I think the current workaround is leaving/closing the channels from slack site itself.

This does not work for me with 1c06c37 (v0.4.0).

**Comment by ykyuen** [comment]
Those `mpdm-*` group are different from channel and there is no way to leave it on slack
https://slack.haash.io/114/how-to-leave-group-messages
```
Group messages are like DMs so you can't leave them, but try closing them out with the "x" or muting them
```

So we need another way to handle them...

**Comment by erroneousboat** [comment]
From the web interface of slack I'm able to "close" the mpim (circle with cross icon, next to the mpim name), and now in branch v0.4.1 it should not be present in the channel overview.
