### ISSUE TITLE
"invalid character '/' looking for beginning of object key string" on open

### ISSUE THREAD

**Issue by joniler** [erroneousboat/slack-term#125]
Installed as instructed, made executable, added slack token; terminal displays:
`2018/03/16 13:07:12 invalid character '/' looking for beginning of object key string`

May be user error.

**Comment by jesselucas** [comment]
@joniler If you copied the config from the README you'll need to remove the comments to make sure the JSON is valid.

**Comment by joniler** [comment]
Omg, duh. Thanks duder.
