### ISSUE TITLE
package does not build

### ISSUE THREAD

**Issue by Mielai1l** [erroneousboat/slack-term#126]
when I try to install slack-term via go, it fails with:
$ go get -t -u github.com/erroneousboat/slack-term 
package context: unrecognized import path "context" (import path does not begin with hostname)

cloning the source with git and building locally gives similar errors

**Comment by erroneousboat** [comment]
Hey @Mielai1l unfortunately I'm not able to reproduce your issue. Would the following work?

```bash
$ go get -u github.com/erroneousboat/slack-term
$ go install .

# alternatively:
$ git clone git@github.com:erroneousboat/slack-term.git
$ make build
$ ./bin/slack-term
```

**Comment by ocket8888** [comment]
I got a +1 on this issue on the Linux Subsystem for Windows (effectively Ubunut Xenial), uname:

```
Linux <hostname redacted> 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

with go version 1.6.3 (standard for Xenial). Error message is the same, no matter how the build is attempted (tested via `go get -u`, as well as the following in the cloned repository directory: `go build slack-term`, `go build .`, `go install slack-term`, `go install .`, `make`, `make test`, `make build`).  
Error message:

```
../github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack/admin.go:4:2: cannot find package "context" in any of:
        /home/<username redacted>/src/github.com/erroneousboat/slack-term/vendor/context (vendor tree)
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /home/<username redacted>/src/context (from $GOPATH)
```

For me, the solution was a toolchain upgrade using the instructions [here](https://github.com/golang/go/wiki/Ubuntu). Using go version 1.10, build/install completed successfully.

Suspect lack of "vendored" packages in lower versions of go is the culprit.

**Comment by erroneousboat** [comment]
@ocket8888 thanks for figuring this out
