### ISSUE TITLE
End to end encrypt

### ISSUE THREAD

**Issue by ppamorim** [erroneousboat/slack-term#131]
Hi,

After reading this article I noticed that Slack is not that secure anymore. So I thought: why not create a end-to-end encrypt between you and the person you are chatting privately? I was trying to do it using the native app for MacOS but it is a little bit messy. So I think to implement this here should be cool.

Article: https://thenextweb.com/apps/2018/03/22/slacks-new-policy-lets-bosses-read-employees-dms-without-consent/

**Comment by erroneousboat** [comment]
I think this is beyond the scope of this project, and as stated in the article as well: _you’re better off avoiding using Slack to do so, and opting for something more secure, like Telegram or Signal_
