### ISSUE TITLE
Blank terminal screen

### ISSUE THREAD

**Issue by saifulmuhajir** [erroneousboat/slack-term#132]
Downloaded binary from releases page but running it gives me blank screen. No error on system.log. Nothing. Looks like it hangs.

```
Version: v0.3.2
Mac OS X Version: 10.13.3
BuildVersion: 17D102
Config: copied from README
```

Tested on iTerm2 as well as default Terminal from Mac.

How I debug this?
Thanks

**Comment by saifulmuhajir** [comment]
Tried to build it myself:
```
go get -u github.com/erroneousboat/slack-term
cd slack-term
go build
./bin/slack-term -config slack-term.json
```

The result is the same.

**Comment by jimkropa** [comment]
Could be because of:
https://news.ycombinator.com/item?id=16567009

?

See also https://opkode.com/blog/slacks-bait-and-switch/

**Comment by erroneousboat** [comment]
It could be that you might have many channels to load, that can take a while. There are changes in branch v0.3.3 that will speed it up, you can check that out and see if the problem still persists.
