### ISSUE TITLE
Secure credentials should be configurable separately

### ISSUE THREAD

**Issue by pappasam** [erroneousboat/slack-term#133]
Like many others, I store my dotfiles on Github. "slack-term.json" cannot be backed up to version control because it MUST contain a valid "slack_token" (which I do not want the world to see).

In order to solve the problem, we would need to configure the parameter "slack_token", and any other potentially security-related parameters, with:

1. Environment variables
2. Command line arguments on startup
3. A separate configuration file that gets merged with the one I store in version control

Options 1 and 2 seem most-promising; maybe both? It looks like config/config.go would need to be updated to handle checks for both the file itself and the existence of the variable in another location.

For reference: http://www.catb.org/esr/writings/taoup/html/ch10s06.html

Please let me know if you'd like my assistance, or if you'd prefer considering this design yourself. Thanks again for building this project and continuing to maintain it!

**Comment by erroneousboat** [comment]
Thank you for the kind words! I agree option 1 and 2 are the more straight forward options. I'll have a look at it.
