### ISSUE TITLE
Consider using `link_names`

### ISSUE THREAD

**Issue by toothbrush** [erroneousboat/slack-term#134]
As a user, when sending a message using `slack-term`, i would like to be able to write something like "Hello @friend" and have Slack automatically convert `@friend` into a link / mention of that user.

I believe that the fix would be simple:  https://github.com/erroneousboat/slack-term/blob/f30310efa6b7534b10c238b5a5a7a4346fea0688/service/slack.go#L276 Add `LinkNames` to this call and set it to true.  Weirdly, the documentation https://godoc.org/github.com/nlopes/slack#PostMessageParameters says the type of `LinkNames` is `int`, but in my experience it should be a `bool`, however i have only used the Slack client in Ruby.

UPDATE: that field is an `int` and is by default set to a constant value defined here https://github.com/nlopes/slack/blob/a22b9657ebc0b4948d7b3a13957c9b75aa55c54c/chat.go#L16. Probably setting it to `1` would work?  To be tested.

**Comment by erroneousboat** [comment]
Present in v0.4.1 (d326f4e3d0c996af63568a8a24c3bca0dbe9f030)
