### ISSUE TITLE
unable to connect 

### ISSUE THREAD

**Issue by pierreraby** [erroneousboat/slack-term#137]
Sorry but I am unable to connect despite a valid token on linux (tested with the pagehttps://api.slack.com/methods/auth.test/test and it's ok ).

I have the following message : 

`not able to authorize client, check your connection and if your slack-token is set correctly`

I've tested with cli flag and env variable too, but same error.

Any idea ?

Thank's in advance

**Comment by erroneousboat** [comment]
Can take a look at: https://github.com/erroneousboat/slack-term/issues/72 and see if it is the same issue?

**Comment by pierreraby** [comment]
Thank's for your response
I don't use vpn and I'm at home with ISP router.
I'll test the application tomorrow from another access point, to see if it changes anything.

**Comment by pierreraby** [comment]
No connection problems with another slack client in node.js that also uses websockets and legacy token ...
Very strange.

**Comment by pierreraby** [comment]
Is really my system, no problem at friend's on the same distribution with same version

I'll find out why

**Comment by erroneousboat** [comment]
Ok, good luck. Thanks for the feedback!

**Comment by TheApeMachine** [comment]
If anyone runs into this again, try removing the comments from the JSON config, that worked for me.
