### ISSUE TITLE
Feature Request - not selecting the channels as you scroll through them / jump to "notification"

### ISSUE THREAD

**Issue by ventz** [erroneousboat/slack-term#139]
Hi,

Great client first of all -- thank you so much for creating it!

Would it be possible to add an option to scroll through the channels without selecting/"actively opening" them? A bit like the old console clients (ex: mcabber [jabber], pork [aim], irssi, etc)

The main issue is that if you are trying to get to a channel, you end up scrolling past a few and it marks the conversations as read. A lot of the times you don't want to read those yet.

Also, would it be possible to implement something like the ctrl/cmd+K in slack -- where it lists or just jumps to channels that have activity? That way you can very quickly jump to "active conversations" rather than scrolling back and forth. I believe both mcabber and pork used to do this with "tab".

Thanks.

**Comment by oliverseal** [comment]
Following the vim-ish bindings I think this should be the key `'`.
