### ISSUE TITLE
Terminal display - display issues - on a mac (TERM + LC_ALL set correctly)

### ISSUE THREAD

**Issue by ventz** [erroneousboat/slack-term#140]
I am trying to figure out what's causing this:

![terminal](https://user-images.githubusercontent.com/901168/39441084-c72a4ee6-4c7a-11e8-8349-8feda51c9422.png)

Specifically - the left/right vertical being "broken" into lines rather than a nice ncurses like display.

Usually it's some combination of term/terminfo/termcap.
On a mac, usually ```color_xterm``` seems to work nicely with console clients.

I've tried ```xterm```, ```rxvt```, and ```nsterm``` - all have the same issue (and I do have the termcap for each).

The other issue is usually around ```LC_ALL``` of UTF vs C -- in this case, both have no effect.

Not sure what else would cause this. A few other console clients seem to work / break correctly as the TERM/LC_ALL changes, but with ```color_xterm```, the rest display properly.

Have you seen this before?

Thanks.

**Comment by erroneousboat** [comment]
Because slack-term uses [termui](https://github.com/gizak/termui), I tried to find a reported issue there that might be the same as your unfortunately I haven't found one, and I've not seen this before. Maybe others have seen this before.

**Comment by ventz** [comment]
Thanks. Is TermUI still supported/maintained? (I can ask there, but it looks like it hasn't been updated in a long time)

**Comment by erroneousboat** [comment]
Doesn't seem like it anymore, that's one of the reasons why I eventually want move away from termui (https://github.com/erroneousboat/slack-term/issues/86). You could try one of their example, depends if you're somewhat familiar with go.
