### ISSUE TITLE
image support

### ISSUE THREAD

**Issue by uhdang** [erroneousboat/slack-term#147]
I am wondering if there is any plan on adding a feature that shows images in regular terminal ? I love using slack-term and it wud be even cooler to be able to view images in it.

**Comment by erroneousboat** [comment]
I think this a bit beyond the scope of this project. And I don't look forward supporting this feature on several systems and/or terminals.

**Comment by JeremyHargis** [comment]
Isn't image support a key feature of Slack?

**Comment by erroneousboat** [comment]
From #130 

> I appreciate the sentiment, however my intention for this project is not to make a feature complete alternative to the official slack client. It's cool that people want to use slack-term as an alternative, but I started this project because I wanted to send and receive message from the terminal to slack, at the time this is/was also possible using other alternatives: weechat or using similar programs to slack-term. I never set out to make a "better" slack-client.

**Comment by aminancelot** [comment]
libcaca could be leveraged though... http://caca.zoy.org/wiki/libcaca
