### ISSUE TITLE
Configurable layout

### ISSUE THREAD

**Issue by superlgn** [erroneousboat/slack-term#149]
Hi,

I've been playing around with slack-term the past few days and it's pretty nice. Very lightweight compared to some of the other Slack clients out there. As a long time xchat/hexchat user I personally prefer to have the channel list on the right side of the window and I was wondering if you ever thought about making the column layout configurable.

Some people may want to be able to fully customize the layout, perhaps switch the rows and the columns, but I'm just looking to move the channel list and command mode columns to the right. I figure that'd probably be the most common alternate layout.

I found the row/column layout in context/context.go. Doesn't seem like it's enough to just swap the NewCol() calls. The input and command mode are fine, but the chat and channel list is garbled up. truncated at different lengths on each line. It almost looks like the length of the visible chat text is related to the length of the channel name, as if the chat text was rendered over the visible area of the channel list and something is filling in / truncating what's left after where the channel name would end (in its original position), if that makes any sense. If I change the channel selection the chat renders and updates properly as new messages come in, but the channel list is empty. No text, just the selection bar moving up and down.

I'm in over my head at the moment so I'm not going to have any code or a proper patch to submit with this RFE. Just thought I'd throw it out there for now.

Thanks,

Mike

**Comment by erroneousboat** [comment]
Now with threads support this is likely not going to happen, since there has been some work done that pretty much enforces the current layout. Has mainly to do with how termui works. When/if slack-term uses a different terminal ui package we can revisit this.
