### ISSUE TITLE
Operating on WSL

### ISSUE THREAD

**Issue by mgarcia-accesso** [erroneousboat/slack-term#152]
I found a single issue already closed concerning operation on WSL (bash for windows) but with no real solution. It seems to be that the implementation of raw sockets is what causes headaches for go apps on WSL. Is there any chance of changing the implementation to utilize tcp sockets instead? Or is this tied directly to the utilization of gorilla websockets?

**Comment by erroneousboat** [comment]
Unfortunately, no. slack-term depends on [nlopes/slack](https://github.com/nlopes/slack) which uses websockets to create real time messaging.

Related: #113
