### ISSUE TITLE
Please word wrap with considering width of characters.

### ISSUE THREAD

**Issue by ozero** [erroneousboat/slack-term#159]
I typed below in slack.

> A1234B1234C1234D1234E1234F1234G1234H1234I1234J1234K1234L1234M1234N1234O1234P1234Q1234R1234

> あ123い456う789え123お456か789き123く456け789こ123さ456し789す123せ456そ789た123ち456つ789てとなにぬねのはひふへほ

then shown good.

![straight](https://i.imgur.com/Sj92A6b.jpg)

and when terminal resized, some characters were lost at word wrapping.

![wrapped](https://i.imgur.com/NxccVQo.jpg)

(lost "9す123せ456そ7" in sample above )

--

I think the word wrapping of Termui may assumes that every characters have same width, then fails (can't fix on slack-term, perhaps). Thats right?

**Comment by erroneousboat** [comment]
Yeah, I also suspect it has to do with termui. I'll have a look.
