### ISSUE TITLE
Par and border color

### ISSUE THREAD

**Issue by ykyuen** [erroneousboat/slack-term#161]
First of all thanks for creating this beautiful slack client. i dun like the official electron slack client and this terminal client looks really good!

I installed the slack-term `v0.4.1` and got a question about the color settings. i hv an archlinux laptop with termite in i3-wm. everything works cool except colors config, here is what set
```
  "theme": {
    "view": {
      "fg": "yellow",
      "bg": "black",
      "border_fg": "red",    // <- not working?
      "label_fg": "red",     // <- not working?
      "par_fg": "red",       // <- not working?
      "par_label_fg": "red"  // <- not working?
    },
    "channel": {
      "prefix": "",
      "icon": "",
      "text": "fg-magenta"
    },
    "message": {
      "time": "fg-red",
      "name": "fg-cyan",
      "text": "fg-green"
    }
  }
  }
```
![sc-2018-09-29-21-19-36](https://user-images.githubusercontent.com/281210/46246275-85abc780-c42d-11e8-9721-f8de377f6769.jpg)

- `border_fg` is the border color i guess.
- `label_fg` is the `Channels` and `slackbot` text color on the top left hand corner and the default is green and bold.
- **but i don't know what is `par_fg` and `par_label_fg`**.

and in the `config/theme.go`, there is a typo at [line 13](https://github.com/erroneousboat/slack-term/blob/v0.4.1/config/theme.go)
```Go
LabelFg string `json:"border_fg"` // should be json:"label_fg"?
```

Thanks again for building this cool app!

**Comment by erroneousboat** [comment]
Hey, thank you for the kind words! I'll have a look why this might happen. Also thanks for testing v0.4.1, let me know if you encounter any issues.

**Comment by ykyuen** [comment]
Thanks for the fix, i have just tried it and the border color works like charm~

for the label color, it still doesn't work which is caused by the wrong mapping in theme.go.

```diff
diff --git a/config/theme.go b/config/theme.go
index 28070fc..4e2e73c 100644
--- a/config/theme.go
+++ b/config/theme.go
@@ -11,8 +11,8 @@ type View struct {
        Bg       string `json:"bg"`        // Background text
        BorderFg string `json:"border_fg"` // Border foreground
        BorderBg string `json:"border_bg"` // Border background
-       LabelFg  string `json:"label"`     // Label text foreground
-       LabelBg  string `json:"label"`     // Label text background
+       LabelFg  string `json:"label_fg"`  // Label text foreground
+       LabelBg  string `json:"label_bg"`  // Label text background
 }
```

After i patched the theme.go files as above locally. the label color works too~

thanks again~ D

**Comment by erroneousboat** [comment]
Yes, I'll fix that as well, thanks!
