### ISSUE TITLE
Borders/boxes changed in 0.4.1?

### ISSUE THREAD

**Issue by popey** [erroneousboat/slack-term#166]
I'm maintaining the [slack-term snap](https://snapcraft.io/slack-term). On 0.4.0 built with golang 1.7, the boxes looked like this.

![image](https://user-images.githubusercontent.com/1841272/47616118-3d290d80-dab0-11e8-9182-5dac3dce699c.png)

After the 0.4.1 release of slack term, I needed to [bump](https://github.com/snapcrafters/slack-term/pull/4) to golang 1.8. Now the boxes look like this.

![image](https://user-images.githubusercontent.com/1841272/47616130-6cd81580-dab0-11e8-85f3-05bf2e620918.png)

Is this an intentional change? Are you typically building on golang 1.8 or something newer? Would be good if we synced those.

**Comment by erroneousboat** [comment]
Hi Alan, no not intentional. I forgot to mention in the release notes that there was a breaking change in the config. #161 mentions the change. I'll update the release notes. The `view` section of `.slack-term` should resemble the following structure:

```javascript
{
  "view": {
    "fg": "white",
    "bg": "default",
    "border_fg": "yellow",
    "border_bg": "blue",
    "label_fg": "yellow",
    "label_bg": "blue"
  }
}
```

**Comment by popey** [comment]
Awesome, thanks. Looks much better :)

![screenshot from 2018-10-29 12-23-00](https://user-images.githubusercontent.com/1841272/47649515-6c558280-db75-11e8-8817-04bf6506876e.png)
