### ISSUE TITLE
Configuration file path

### ISSUE THREAD

**Issue by abacao** [erroneousboat/slack-term#170]
Please consider looking the configuration file not only in ~ but also in ~/.config/slack-term/config (or even change it to this path)

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

https://unix.stackexchange.com/questions/312988/understanding-home-configuration-file-locations-config-and-local-sha

**Comment by lhanson** [comment]
@erroneousboat Is this a feature you'd merge if a PR was submitted?

**Comment by jrwrigh** [comment]
@lhanson The logic to do it is pretty simple from what I can tell (I admittedly have no idea what I'm doing in Go). See my first comment in #203 for the specific function that (probably) needs to be changed.

**Comment by lhanson** [comment]
@jrwrigh Excellent, thanks for that info.

**Comment by erroneousboat** [comment]
Reference #203

**Comment by erroneousboat** [comment]
Ok, at the moment I don't see the merit of using XDG Base Directories other that a "clean" home directory. I'll have a look at the links provided here, but seeing from the PR needing to have additional knowledge of XDG Base Directory Specification, and explicitly setting it doesn't really seem that of an improvement. I'd rather have it as is, with the option to specify from the command line where the config file is.

**Comment by lhanson** [comment]
Please do at least skim the spec and/or some of the justifications for it to understand why this is a win for everybody. Implementing the spec costs nothing from either a user's or a maintainer's perspective, and has many benefits.

> needing to have additional knowledge of XDG Base Directory Specification, and explicitly setting it doesn't really seem that of an improvement

There is no assumption that users have ever heard of the specification, and no requirement for them to explicitly configure anything. The specification provides sensible defaults for the case where the variables aren't set, which will be most of the time. Users who don't know what the spec is will have their files stored in reasonable locations. Users who *are* aware of the spec and are fine with the defaults won't have to set anything. People with special use cases where they want to specify particular paths (a small minority of users) can set the environment variables accordingly. Without following the spec, none of those users would likely guess that `$HOME/.slack-term` is the magic config path without being told anyway.

As for tangible benefits, here are a couple off the top of my head:
* Users can back up or version control all of their configurations from a single directory subtree. Sync `$XDG_CONFIG_HOME` and you're done. Contrast that with having to maintain a list of snowflake directories for each application which doesn't follow the spec, likely with regexen and exceptions in cases where an application doesn't use distinct directories for configuration vs. data vs. cache.
* Users can rely on the fact that data in `$XDG_CACHE_HOME` can safely be deleted to free up space, or in some privacy-sensitive applications (VPN users in repressive countries) they may want to explicitly do so after every session anyway.

**Comment by erroneousboat** [comment]
Alright, thanks I'll have a look

**Comment by erroneousboat** [comment]
For the developer:

* <https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html>
*<https://unix.stackexchange.com/questions/312988/understanding-home-configuration-file-locations-config-and-local-sha>
* <https://wiki.archlinux.org/index.php/XDG_Base_Directory>
* <https://wiki.gnome.org/action/show/Initiatives/GnomeGoals/XDGConfigFolders?action=show&redirect=GnomeGoals%2FXDGConfigFolders>
* <https://wiki.debian.org/XDGBaseDirectorySpecification>
* <https://wiki.debian.org/UpstreamGuide#User_home_directories>
* <https://ploum.net/207-modify-your-application-to-use-xdg-folders/>

**Comment by erroneousboat** [comment]
Reopening issue, not yet merged.
