### ISSUE TITLE
Highlight channels with existing unread messages

### ISSUE THREAD

**Issue by lennartkoopmann** [erroneousboat/slack-term#174]
When starting slack-term and I have unread messages already, I don't get the asterisk in front of the channel. Only unread messages that are received while the app is running are highlighted.

rel #60

I'm on v0.4.1 linux-amd64.

Thank you so much for this project! I do really enjoy it.

**Comment by yousafsyed-bg** [comment]
An option to show channels with unread messages only would be interesting
