### ISSUE TITLE
Does slack-term updates your online status to others?

### ISSUE THREAD

**Issue by xescugc** [erroneousboat/slack-term#175]
Hello!

First of all, thanks for this amazing project!

I've been using `slack-term` for a long time and some coworkers noticed that I'm always "offline" (just the green orb on the names).

I was wondering if `slack-term` handles it, and if not if it's possible.

I possible I could do it :smile:

**Comment by erroneousboat** [comment]
Hey, thanks man! No you're right it should be set, I'll have a look if I'm able to reproduce it.
