### ISSUE TITLE
Lengthy URL get wrapped and then truncated when clicked

### ISSUE THREAD

**Issue by valentinrusu-movidius** [erroneousboat/slack-term#177]
Colleagues occasionally send me links to Web pages.

We're using here lengthy URLs that wrap to next line before their end. The first part, displayed on the first line, is clickable but leads to a truncated URL. The missing part is exactly the part that wrapped into the second line. Also, that second part is not clickable.

I would've expected at least to get the full URL when I clicked the first part. Ideally I would expect both parts to be clickable and lead to the correct, original, URL.

Thanks for this great text mode tool :-)

**Comment by erroneousboat** [comment]
Whether an url is clickable or not depends on the used terminal emulator. As far as I can see I'm not able to create a solution for this in slack-term. There is also a question about this (#168) with a potential workaround which I use personally.
