### ISSUE TITLE
More info with integrations

### ISSUE THREAD

**Issue by xescugc** [erroneousboat/slack-term#179]
When a user uploads a file/image to slack (or use giphy hehe) or other integrations, the content it's hidden on `slack-term`.

For example with Trello integration the name of the user is `<unknown>` but on slack they show more info (title, card, board) IDK if that it's send thought.

On upload the content it's directly `<unknown>` only the titles is shown, if any. Would be good to have the slack URL for it.

For giphy it's the same as uploads, `<unknown>` and a title is what it was search with. This is not a requirement but just that it's the same behavior as the others so I would say that it would follow the same approach.

Seems related to https://github.com/erroneousboat/slack-term/issues/13 but IDK I still see it wrong.

**Comment by erroneousboat** [comment]
I'll have a look if I can atleast get the url from file/image to show

**Comment by erroneousboat** [comment]
Added files download link to messages, that fixes the first part of the issue.

Second part, more info with integrations, I'll reopen the issue
