### ISSUE TITLE
Channel panel width?

### ISSUE THREAD

**Issue by masivi** [erroneousboat/slack-term#180]
Is possible to change the width of the channels panel? I can't see the name of the channels because the collumn is too small.

Thank's for the good job!

**Comment by Julioevm** [comment]
Put "sidebar_width": 2 in your config file. 2 being the desired size value.

**Comment by masivi** [comment]
Thank's!

My .slack_term file is:

{
    "slack_token": "xoxp-..."
    "sidebar_width": 2
}

token complete, of course.
Error:
2019/03/07 14:40:26 the slack-term config file isn't valid json: invalid character '"' after object key:value pair

Any idea?

**Comment by Julioevm** [comment]
Missing a comma ',' after the first value. use this:
{
"slack_token": "xoxp-...",
"sidebar_width": 2
}

**Comment by masivi** [comment]
Right!!!!

Thank's a lot!!!!
