### ISSUE TITLE
FEATURE: Filter up new messages 

### ISSUE THREAD

**Issue by serussell** [erroneousboat/slack-term#185]
I would like a way to more easily identify channels with new messages.

The use case is someone who has dozens of channels and 1:1 conversations, such that paging through the list to review all of them is required.  Currently, there is no paging shortcut, so scrolling through the list is required; however, even if keys for paging the channel list existed, it would still require some effort to identify channels with new messages.  I'd like a way of grouping the channels with new messages, to more easily identify, navigate to, and address them.  I don't have a preferred idea, but a couple that come to mind are:

1. A second, separate list at the top of the channel list, containing only channels with unread messages
2. Auto-sorting channels with new messages to the top of the list

**Comment by hellojoshuatonga** [comment]
I'd also like to have this. Hope that we can have this

**Comment by erroneousboat** [comment]
On the master branch there is a commit which allows you to jump to channels that have new messages (#139)

**Comment by erroneousboat** [comment]
Closing this in favour of #139
