### ISSUE TITLE
FR: Highlighted channel bg

### ISSUE THREAD

**Issue by sprnza** [erroneousboat/slack-term#190]
Hi there!
I've failed to find an ability to set a selected channel bg. It would be great to have such an option in the "channel" object of the theme settings. Thanks!

**Comment by sprnza** [comment]
Okay, let put it this way. What color is currently being used for highlighting selected chats and coloring cursor in the Insert mode? I've got it the same as for the maing background so I don't see what chat is selected and the cursor is invisible.

**Comment by erroneousboat** [comment]
You can change it in the config file by changing the value of `view > fg`, however I admit this isn't clear or intuitive. I'll see if I can fix this.

**Comment by sprnza** [comment]
Hi! Thanks, that works!
