### ISSUE TITLE
Edit the sent message

### ISSUE THREAD

**Issue by zshamrock** [erroneousboat/slack-term#191]
Unless I missed this from the documentation, is there currently the way to edit the sent message? Like in the official Slack app, by pressing arrow up brings the sent message to allow to edit and send it back?

**Comment by zshamrock** [comment]
If it is not there, and we consider this is a valuable feature to have (at least I would like to), can contribute with the PR.

Although be honest have not checked the code yet, so have no idea so far whether it is feasible to do. But if you confirm it is, then I can pick it up and start working on it.

**Comment by erroneousboat** [comment]
No there is not option to edit the message.

**Comment by erroneousboat** [comment]
Closing this, at the moment I'm not keen on implementing this.
