### ISSUE TITLE
"assignment to entry in nil map"

### ISSUE THREAD

**Issue by xescugc** [erroneousboat/slack-term#193]
Some times I get this error:

```
panic: assignment to entry in nil map

goroutine 31 [running]:
github.com/erroneousboat/slack-term/components.(*Chat).AddReply(...)
	/go/src/github.com/erroneousboat/slack-term/components/chat.go:189
github.com/erroneousboat/slack-term/handlers.messageHandler.func1(0xc0003f40e0)
	/go/src/github.com/erroneousboat/slack-term/handlers/event.go:136 +0x469
created by github.com/erroneousboat/slack-term/handlers.messageHandler
	/go/src/github.com/erroneousboat/slack-term/handlers/event.go:117 +0x3f
```

It's somewhat declarative hehe

**Comment by erroneousboat** [comment]
This is on master, trying to reply to a thread, right? I'll have a look at it.

**Comment by xescugc** [comment]
It's on master, and it's not actually on reply, It "randomly" fails so I would assume that it's when a reply on a thread is received and tries to find the parent to show the message. But I can not reproduce it with clarity sorry :(.

I see why it fails in code and those are my assumptions, what I can say is that there was no action taken by me :).

**Comment by erroneousboat** [comment]
Cool thanks for the context!

**Comment by xescugc** [comment]
Just to give ideas, could be related that a thread is fetch on the history but not the parent message? as it's out of the "page history"?

**Comment by erroneousboat** [comment]
Yeah I also expect this to be the case

**Comment by erroneousboat** [comment]
The last commit should help with getting the fatal error. When a parent id isn't present in the chat view it will just add the message. This is for now a workaround, because it doesn't relay that it is a reply to a thread, which might get confusing.

**Comment by xescugc** [comment]
Also, this would potentially be fixed also with the `v2` on threads :smile: .

**Comment by xescugc** [comment]
Also, this would potentially be fixed also with the `v2` on threads :smile: .

**Comment by erroneousboat** [comment]
Closing this for now to clean up issues. Reopen when it continues to be a problem
