### ISSUE TITLE
History Timout

### ISSUE THREAD

**Issue by xescugc** [erroneousboat/slack-term#195]
I can not give more context as it's self explanatory:

```
2019/06/11 18:24:34 Post https://slack.com/api/conversations.history: dial tcp xx.xxx.x.xxx:xxx: i/o timeout
```

I open the issue just to know if quitting the app it's the expected behavior or not.

I think it took a while when opening a channel, then I moved up and then down, and the channel messages showed up, so i feel it was a 1st call Timeout even if the 2nd one succeeded (I did not read the code so just guessing). So I ended up with a behavior of quitting the app even if nothing wrong happened hehe.

**Comment by erroneousboat** [comment]
Don't know if this is perhaps a connection timeout of the client. Spotty internet, wifi connection perhaps?

**Comment by xescugc** [comment]
IDK really :cry: . Also IDK if this happens to everyone, but when it fails the terminal it's messed up, to actually see the errors I have it like `slack-term -config .slack-term.json &> error.txt` so I can actually get a more "proper" error hehe. IDK if there is a way to have a more "clean" quitting or to maybe have the errors shown somewhere (maybe replacing the content of the channel?) IDK really hehe.

**Comment by erroneousboat** [comment]
Closing for now, hard for me to get this to actually happen. I'll keep a lookout
