### ISSUE TITLE
Panes are misaligned on the Ubuntu terminal

### ISSUE THREAD

**Issue by nshdesai** [erroneousboat/slack-term#196]
I've been using `slack-term` on an Ubuntu 18.04 system (installed with snap). After running the code a bunch of times, the UI for this CLI client suddenly broke (refer to attached screenshot). Can't seem to find a fix.
![slack_terminal_misaligned](https://user-images.githubusercontent.com/19650855/59318407-fb428580-8c94-11e9-9913-b5b8ca1e7819.png)

^ that is the channel pane and the "mode pane" section of the UI

**Comment by erroneousboat** [comment]
Don't know exactly what is going on, could be a font issue perhaps? I'll leave it open, perhaps others experience the same problem.

**Comment by nshdesai** [comment]
I think I found the problem/solution...

In an attempt to enable emoji support on my terminal. I changed the ambiguous-width characters to 'wide' in my terminal preferences. Unfortunately this did not work (the emoji thing). Simply switching the setting back to narrow ambiguous width characters happened to solve the issue.
