### ISSUE TITLE
Brand new groups do not show up

### ISSUE THREAD

**Issue by xescugc** [erroneousboat/slack-term#198]
When you are invited to a new group it does not show up on the list, but you are able to receive notifications from it, which are assigned to the channel on position 0 (default int I assume hehe) so you receive desktop notifications of a channel that may not have activity from a group that you don't see, but the messages are not there, on the position 0 (as it's not the right place either).

It may also happen with Channels and others but IDK.

**Comment by xescugc** [comment]
Mmm after looking again (and restarting slack-term) I think that the group was "reactivated" because it was on the list before but the messages where not recieved there. Maybe when groups are reactivated (meaning created again with the same people) something strange happens.

**Comment by erroneousboat** [comment]
Closing for now, lets see if this will happen again
