### ISSUE TITLE
Create an 'official', Automated Build Docker image on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [erroneousboat/slack-term#200]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags from git tags & branches.
Also, documentation could easily include a canonical `docker run` statement to quickly run slack-term with just a single command.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags.
Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Docker search command clearly displays AB when listing images:
```
$ docker search slack-term
NAME                          DESCRIPTION         STARS               OFFICIAL            AUTOMATED
kristianp/slack-term          slack terminal ui   0                                       
mego22/slackterm              slack-term image    0                                       [OK]
pataquets/docker-slack-term   slack-term          0                                       [OK]

```
Just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by erroneousboat** [comment]
Yes, good idea. I've already created the Dockerfile and I'll make the necessary changes to support the automatic builds. Thanks for the offer, I'll take you up on it when necessary. Cheers

**Comment by erroneousboat** [comment]
Should be working at https://hub.docker.com/repository/docker/erroneousboat/slack-term

Closing this to clean up the issues, if it doesn't work reopen the issue.

**Comment by pataquets** [comment]
Great, thanks!
It works, so far. Let's see if I manage to get used to it and can test it thoroughly.

**Comment by pataquets** [comment]
@erroneousboat : When running term tools under Docker, I always find useful adding the following switches to the `docker run` command to pass my host's environment variables:
```-e TERM -e COLUMNS -e LINES -e LANG -e LC_ALL -e TZ```
I'm not sure about which ones `slack-term` makes use of, since I always just add them all just in case. You might be interested in adding those really useful to the Readme. It even might get rid of the `stty` call in the Dockerfile `ENTRYPOINT`: `slack-term` correctly resizes as I resize the term window.

**Comment by erroneousboat** [comment]
@pataquets Hey, thanks for testing it out. I'll have a look what env vars are useful to pass through. Considering replacing the `stty` I'm a bit hesitant, because I like the readme and the docker run command to be as concise as possible. If you have other docker images that you use that use similar strategies let me know so I can inspect them, and see how they tackle it.
