### ISSUE TITLE
XDG Base Directory Support

### ISSUE THREAD

**Issue by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [erroneousboat/slack-term#203]
Could support of [XDG Base Directories](https://wiki.archlinux.org/index.php/XDG_Base_Directory) be considered? It would be nice to be freedesktop.org compliant and use XDG base directories by default. I know that this has been suggested [before](https://github.com/erroneousboat/slack-term/issues/118#issuecomment-377650941) but nothing came of it. So instead of placing a hidden file directly in the home directory, placing it in `$XDG_CONFIG_HOME/slack-term.json` which is usually `~/.config/slack-term.json`. This prevents home directory pollution which I personally can't stand.

**Comment by jrwrigh** [comment]
I was about to write an issue for this exact thing. It should probably still check `$HOME/` for backwards compatibility sake. Unfortunately, I don't know Go so I can't fix the issue in a reasonable amount of time.

For anyone wanting to take a stab at it, it looks like all that would need to be changed is simply put some logic at the function on line [55-60 of main.go](https://github.com/erroneousboat/slack-term/blob/bc11d9891af52191ffa30b8e24c45a976f74e996/main.go#L55-L60). Simply a "check `$HOME/.config/` for `slack-term.json`, otherwise use $HOME" is all that'd be necessary from what I can see.

**Comment by jrwrigh** [comment]
Also, repeat of #170 (though without the exact XDG terminology).

**Comment by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [comment]
Note that the specification specifies that `$XDG_CONFIG_HOME` must be checked before falling back to `$HOME/.config`, before falling back to how it is now. Although I've never heard of anyone not setting `XDG_CONFIG_HOME` to `$HOME/.config`.

**Comment by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [comment]
Some more background (besides the original Arch wiki link) for the unfamiliar:

https://wiki.gnome.org/action/show/Initiatives/GnomeGoals/XDGConfigFolders?action=show&redirect=GnomeGoals%2FXDGConfigFolders

https://wiki.debian.org/XDGBaseDirectorySpecification

**Comment by jrwrigh** [comment]
Gotcha. I updated my comment in case anyone finds this and just reads my comment on the directories to be checked.

**Comment by lhanson** [comment]
I'm happy to write a patch for this, but was hoping to get some confirmation from @erroneousboat that this would be a feature which they'd merge. I've encountered the odd maintainer who is either recalcitrant to adhere to the XDG spec or is unresponsive and the PR just sits in limbo forever. Not saying that's the case here, but it's nice to ask first before expending the effort when I've got a list of other projects I use which could use the same attention.

**Comment by lhanson** [comment]
Patch submitted, enterprising users can run my branch if they don't want to wait for it to be merged.

Looking at the commit history and the number of dormant PRs open, it seems like this project isn't actively maintained or is only given sporadic attention. If @erroneousboat  wants some help maintaining the project I'm sure some community members would be interested in having a more up-to-date repo! I don't even use Slack that much anymore but would be willing to help.

**Comment by erroneousboat** [comment]
Closing this in favour of #170
