### ISSUE TITLE
Left pane too narrow although window is quite wide

### ISSUE THREAD

**Issue by luciusbob** [erroneousboat/slack-term#209]
On my terminal the left pane is very small although the window itself is quite wide.
Can I somehow fix it? I haven't found a config for the single panes.

Version:0.4.1 on Ubuntu 18.04 wayland
Installation method: snap

![Screenshot_slack-term](https://user-images.githubusercontent.com/27236491/65594808-c16f6380-df93-11e9-89ca-1928b6a7657e.jpg)

**Comment by erroneousboat** [comment]
See wiki `sidebar_width` (https://github.com/erroneousboat/slack-term/wiki#slack-term-config-file)
