### ISSUE TITLE
Hitting rate limits on first use

### ISSUE THREAD

**Issue by looneym** [erroneousboat/slack-term#211]
Hey 👋 

Thanks for the software.

I'm running into the same problem described in https://github.com/erroneousboat/slack-term/issues/167 which has been closed. There are a number of similar comments on the closed issue but I'm reopening for visibility. 

I'm on `v0.4.1` on Linux using a legacy token and my workspace is probably huge. 

LMK if there's anything else you need

**Comment by erroneousboat** [comment]
Change is done on master branch, not on any release. So issue is fixed, but requires you to build slack-term. Leaving this open indeed for visibility, I'm getting everything ready for next release. Blocking was mainly the threads functionality, which was a pain to get working correctly.

**Comment by looneym** [comment]
Ah thanks a lot. Sorry I didn't spot that this wasn't released. Thanks again I'm excited to use this!

**Comment by punkdata** [comment]
@looneym I was getting the rate limit error as well & I can confirm building the app from src and using that binary resolves this issue

**Comment by erroneousboat** [comment]
Removing this question since it shouldn't be relevant with the new release
