### ISSUE TITLE
Put channels with unreads on the top of the list

### ISSUE THREAD

**Issue by ghaabor** [erroneousboat/slack-term#22]
So you see when you have unread messages if the list of channels cannot be rendered in 1 terminal window.

**Comment by erroneousboat** [comment]
Channel with unread messages have an specific icon in front of them, I'm leaving the ordering up to the slack service. Channels, Groups, IM.

**Comment by nicklan** [comment]
When you have a lot of channels, the above answer is really not sufficient.  Not every channel I'm in is even visible at once, meaning I have to do a bunch of scrolling just to check for new messages.  This makes slack-term pretty much unusable.  Moving unreads should really be a feature (via an option probably)

**Comment by harimp** [comment]
I find scrolling down to the new one is a constant annoyance to work with. I think it's really useful to add either this feature or a feature to skip to next unread channel/mpdm/user via key command.

**Comment by acaloiaro** [comment]
FYI @nicklan @harimp @ghaabor I have a PR that achieves a similar result if you're interested https://github.com/erroneousboat/slack-term/issues/214
