### ISSUE TITLE
Unsupported block type

### ISSUE THREAD

**Issue by ConnerEnders** [erroneousboat/slack-term#224]
v0.4.1
Installation method: Go

slack-term was consistently crashing on specific channels getting this message: 
(timestamp) unsupported block type

I traced the problem to the github.com/nlopes/slack package and the problem is related to an API change from Slack. I believe they have a pending PR to fix this issue, but for the time being, if you would like to fix this issue, you need to make some changes to $GOPATH/pkg/mod/github.com/nlopes/slack@v0.6.0/block_conv.go

Here are those changes: https://github.com/nlopes/slack/issues/630#issuecomment-553105244

While this problem is not directly related to this repo, I thought it might be useful to make a note here for others who are unable to use slack-term at the moment.

**Comment by xescugc** [comment]
I'm gonna say it's this issue https://github.com/erroneousboat/slack-term/issues/212

**Comment by ConnerEnders** [comment]
> I'm gonna say it's this issue #212

Oh yes it is, didn't see that issue. This is irrelevant then.
