### ISSUE TITLE
Throws on go get command on arm aarch64 (debian).

### ISSUE THREAD

**Issue by MathieuDSTP** [erroneousboat/slack-term#233]
Following your reply for a maybe similar error on Mac OSX (#59 ),
I get the following error when attempting go get:

.gopathroot/src/github.com/erroneousboat/slack-term/service/slack.go:239: undefined: sort.Slice

Running on debian 4.4 on arm64.
---

Version:
Installation method:

**Comment by erroneousboat** [comment]
Hey, what is the go version that you're using? (`go version`)

**Comment by MathieuDSTP** [comment]
1.7.4 linux/arm

**Comment by erroneousboat** [comment]
Update your go version, and try again.
