### ISSUE TITLE
Add code highlights for single and triple backquotes blocks

### ISSUE THREAD

**Issue by ekhabarov** [erroneousboat/slack-term#24]
Like `this one` and 

```
this
multiline
block
```

**Comment by erroneousboat** [comment]
This is a very specific feature, and I'm not certain how I'm going to display it as something that is easy recognizable from the monospaced font that the terminal uses. Besides that I want to first get the application to support colors for messages, usernames, channels and I'm going to investigate whether gocui would be better than termui.
