### ISSUE TITLE
Question Regarding Permissions / User Token Scopes

### ISSUE THREAD

**Issue by StevenXL** [erroneousboat/slack-term#249]
Hi folks, 

I was wondering what scopes the token that is used with `slack-term` should have.

I running `slack-term --token <mytoken>` and it said that a scope was missing, but not which one.

The token I was using had the following scopes:

1. channels:read
2. chat:write
3. files:write
4. groups:read
5. users:read
6. users:read.email

**Comment by 80aff123-9163-4f3e-a93d-4a2f35af9be1** [comment]
I got a similar error today:

```sh
$ slack-term
2020/10/30 20:45:07 missing_scope
```

I am using slack-term 0.5.0 installed from this [nix expression](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/instant-messengers/slack-term/default.nix#L18)
