### ISSUE TITLE
project doesn't follow normal go package layout

### ISSUE THREAD

**Issue by tmc** [erroneousboat/slack-term#28]
Versioning binaries is odd and you're not following the typical cmd/${cmdname}

When i go get this package i get a 'src' binary on my PATH.

**Comment by ronelliott** [comment]
not to mention cloning this repo takes way too long. the .git directory is 51MB, and the bin folder is 20MB. please move everything from the src folder to the repo root, and remove the bin and src folders.

**Comment by erroneousboat** [comment]
https://github.com/erroneousboat/slack-term/commit/d2fb5c06d925998c8ece88827b9bd47f7ba5b15e

@tmc does this fix the 'src' binary problem?
@ronelliott I've removed the `bin/` folder

**Comment by tmc** [comment]
@erroneousboat that's better
