### ISSUE TITLE
It's impossible to type non-ASCII text

### ISSUE THREAD

**Issue by pixelbender** [erroneousboat/slack-term#30]
It displays cyrillic correctly but typing is not possible.
Using iTerm2 v 3.0.10 (UTF-8, xterm-256color mode).

**Comment by mifz** [comment]
confirmed. typing in cyrrilyc and other person got something like "BAD+11BAD+11BAD+11BAD+11BAD+10BAD+10йBAD+B8BAD+BABAD+81BAD+81BAD+83BAD+80"

**Comment by stonevil** [comment]
+1

**Comment by pixelbender** [comment]
Using `len` is not a good idea for runes counting:
```go
t := "Привет"
fmt.Printf("Number of bytes: %d\n", len(t))
fmt.Printf("Number of runes: %d\n", utf8.RuneCountInString(t))
```
Output:
```
Number of bytes: 12
Number of runes: 6
```
So the issue affects all non-ASCII input.
