### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by silviogreuel** [erroneousboat/slack-term#50]
I know that windows support isn't planned, but it actually works, besides a bug

## Environment
- Windows 10
- Cmder

## Report
- Need to do a double stroke to send commands and write text.

**Comment by erroneousboat** [comment]
To be clear with double stroke you mean you have to press the particular key twice in order to send a command?

**Comment by silviogreuel** [comment]
yes,  sorry for late response.

**Comment by dfdeagle47** [comment]
Seems to work correctly using the Windows PowerShell.

**Comment by KaelBaldwin** [comment]
I'm not noticing the double stroke bug you mention. (using windows 10 and commander as well)

**Comment by hoetz** [comment]
Works great for me on CMD and Powershell, latest Win 10

**Comment by orestesgaolin** [comment]
Could you please elaborate on your installation process on Windows?

**Comment by radzio** [comment]
@hoetz  how did you install it on Windows?

**Comment by hoetz** [comment]
@radzio yep go get

**Comment by orestesgaolin** [comment]
@hoetz I ran `go get -u github.com/erroneousboat/slack-term` as stated in the installation guide but there was no output of any kind, even with administrative rights. Did it work for you on Windows 10?
