### ISSUE TITLE
Snap slack-term

### ISSUE THREAD

**Issue by popey** [erroneousboat/slack-term#51]
slack-term is amazing. The fat slack client eats about 25% of my laptop RAM, and most of the CPU which makes slack-term a fantastic alternative. My laptop CPU fan thanks you!

I took the liberty of making a snap [1] package to make it easy for Linux users to install and use.

"snap install slack-term" will get them the latest stable release, adding "--edge" will get a daily build from git master. It's in the snap store under my name, but I'd love to hand it over to you, so you can manage it and view stats etc.

[1] http://snapcraft.io/

**Comment by erroneousboat** [comment]
Hi @popey, thank you for the kind words, I'm glad you're able to make good use of it! I'll make sure to check out how snap works (I've heard from it, but never tried it). I'm fine with you managing the store, mainly because of my (yet) limited knowledge of snap :)
