### ISSUE TITLE
installation instructions incomplete/not working

### ISSUE THREAD

**Issue by lisaq** [erroneousboat/slack-term#53]
When I follow the README, `slack-term` does nothing; I get `slack-term: command not found`. Surely there's some installation instructions which are missing here?

**Comment by piotr-yuxuan** [comment]
The step about installation is missing. Have you tried `$ go install` then reload your terminal? Moreover you need a working golang install (which means `$GOPATH/bin`) is in your `$PATH`

**Comment by lisaq** [comment]
Thanks for the reply. Note: I've never used go before, so I have a somewhat noob perspective here. I just want be able to use Slack from my terminal.

I did sort out that I needed to install golang but not the rest. I just tried `go install` and got a lot of "cannot find package" errors. Presumably the problem is `$GOPATH` (but what is that? I'll use my googles).

**Comment by erroneousboat** [comment]
You don't need to have go installed on your system to run slack-term. As stated in the readme:

[Download](https://github.com/erroneousboat/slack-term/releases) a compatible version for your system, and place where you can access it from the command line like, `~/bin`, `/usr/local/bin`, or `/usr/local/sbin`.

If then it still doesn't work you, might want to take a look at your `$PATH` (`echo $PATH`), those directories mentioned above should be in there.
