### ISSUE TITLE
invalid character 'j' looking for beginning of value

### ISSUE THREAD

**Issue by rpietro** [erroneousboat/slack-term#54]
I got the token for slack and applied it to slack-term.json, but when I try to initiate the app I get the msg: `ERROR: not able to load config file (~/slack-term.json): invalid character 'j' looking for beginning of value`

any thoughts on what might be wrong?

thanks

**Comment by erroneousboat** [comment]
Could you post your `slack-term.json` file? There might be an error in it.

**Comment by rpietro** [comment]
@erroneousboat that was exactly the problem, was missing a comma. thanks a lot
