### ISSUE TITLE
slack-term does not seem to be installed after running the go get command (OS X Sierra)

### ISSUE THREAD

**Issue by sashaafm** [erroneousboat/slack-term#59]
Hello, I'm experimenting with your Slack CLI client and I've ran the command `go get` to fetch the package like told in the README. However, after installing I don't seem to have the `slack-term` command. I've also tried to look into my `bin` directories but couldn't find anything. 

Maybe I'm using the `go` command in a wrong way, or maybe OS X is not supported?

Tell me if you need any further info

Thanks

**Comment by erroneousboat** [comment]
Hi, the recommended way of installing `slack-term` is downloading the binary. However, I've made some changes to the project that might solve your problem. If you could test it by issuing the following command and post the output of that command when any errors come up.

```bash
$ go get -v -u github.com/erroneousboat/slack-term
```

**Comment by shouse** [comment]
I know this is closed but I can also not access via OSX after running the go command.  it's not found after executing

**Comment by ogirginc** [comment]
When I run `go get -v -u github.com/erroneousboat/slack-term`, all I get is:

```
github.com/erroneousboat/slack-term (download)
```

**Comment by jhirbour** [comment]
I ran into the same issue as the OP trying to install this today.

# tried to install via go

```
$ go get -v -u github.com/erroneousboat/slack-term
github.com/erroneousboat/slack-term (download)
```
No further output here. Could not run slack-term in a terminal

# downloaded the binary into ~/bin

```
chmod u+x ~/bin/slack-term-darwin-amd64
```

```
 ~/bin/slack-term-darwin-amd64
2018/03/07 11:30:38 invalid character '/' looking for beginning of object key string
```

I'm running MacOS High Sierra Version 10.13.3, and have os x developer tools installed (I do ruby dev)

Also has there been any efforts to make this a homebrew package?

**Comment by arkadiybutermanov** [comment]
@erroneousboat , in support of @jhirbour's question: do you think, it's a good idea to create a `homebrew` package for `slack-term`? https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md That would make the upgrade process a lot easier on MacOS.

**Comment by jhirbour** [comment]
@erroneousboat I still can't install this on HighSierra via go or the binary. If you want me to open a new issue, let me know what information would be helpful for troubleshooting.

**Comment by erroneousboat** [comment]
@jhirbour `2018/03/07 11:30:38 invalid character '/' looking for beginning of object key string` is because your `slack-term.json` is not valid json, remove the commented lines to make it valid json. You only need the slack-token the rest is default.

When you've `go get` the project please also issue `go install .` (in the project folder).

**Comment by jhirbour** [comment]
@erroneousboat I  had a trailing , at the end of my config file. I used jsonlint to find it.

**Comment by rni063** [comment]
Having some trouble with the install on Mojave. A homebrew package install would be nice.

**Comment by Jefferson-Faseler** [comment]
I am also having trouble with the install on MacOs.

In `~/go/src/github.com/erroneousboat/slack-term`, running `go install .` produces no output
From `~/go/src/github.com/erroneousboat` running `go install slack-term/` raises
```
can't load package: package slack-term: cannot find package "slack-term" in any of:
	/usr/local/Cellar/go/1.11.5/libexec/src/slack-term (from $GOROOT)
	/Users/jfaseler/go/src/slack-term (from $GOPATH)
```

**Comment by danggrianto** [comment]
using go install run this
```GOBIN=/usr/local/bin/ go install .```
