### ISSUE TITLE
ability to show only subscribed groups/chats

### ISSUE THREAD

**Issue by ajrossnz** [erroneousboat/slack-term#64]
When signing in to slack-term I see all the chats I've ever been on, not just the current ones. I also see all 200 members of staff in my org, as well as all the different project and talk groups. I only want to see the ones I'm subscribed to.

Is there any way to show just those ones?
Also, I seem unable to get search with / working - the mode does not change. Using the example keybindings

**Comment by hholst80** [comment]
I would guess we have a few thousand channels so just *starting* slack-term takes 20 seconds on a 56 core machine with 1 Gbps internet connection. I'd hate to see how long that takes on a 1Mbps connection.

**Comment by m3at** [comment]
@ajrossnz for your second issue adding `"/":       "mode-search"` to command in `slack-term.json` solved it for me.
Keyboard mapping issue maybe? My keyboard has a Japanese layout.

**Comment by erroneousboat** [comment]
Fixed in v0.3.0
