### ISSUE TITLE
Notifications Aren't Correct

### ISSUE THREAD

**Issue by sirplatypos** [erroneousboat/slack-term#65]
When I use this, the notification popup for recipients says that the message is from "Slack API Tester".  Everything else acts the same as it does in the GUI except for this.  Is there any way to fix this?
![pasted image at 2017_10_24 08_39 pm 1](https://user-images.githubusercontent.com/32854229/31974931-d2169a50-b8f3-11e7-9798-715ee40eb31f.png)

**Comment by erroneousboat** [comment]
I might be able to fix this, by setting the username in the `PostMessageParameters`. I'll have a look.

Reference: https://godoc.org/github.com/nlopes/slack#PostMessageParameters
