### ISSUE TITLE
Search improvement: should jump to full match (if any), and/or "jump to next / previous" in search

### ISSUE THREAD

**Issue by viktorbenei** [erroneousboat/slack-term#70]
## The issue

You have a person in the team with the name `xyz`, and you want to jump to a private chat with him/her, but you also have a channel with a name `abc-xyz` which comes first in ABC order.

Right now if I try to jump to `xyz` (using search -> `xyz`) it'll jump to the first item, which is not the private chat of `xyz` but the channel named `abc-xyz`, as that comes first in ABC order.

In fact I have 10+ channels between the two "items" (the `abc-xyz` channel and the `xyz` person / private chat), so all I can do right now is: 

1. Search for `xyz` which will open the `abc-xyz` channel
1. Then `j` `j` `j` .. `j` to get to the private chat with `xyz`

## Proposed solution

1. Whenever there's an exact match, that should be opened. In this example if I type in `xyz` that should open the private chat with `xyz`
1. Have a "next" / "prev" key mapping in search, just like `n` / `N` is in vim search for example, to jump to next / previous found item.

---

P.S.: awesome project, keep up the great work! :)

**Comment by erroneousboat** [comment]
Hey, thanks! I'm glad that you like the application. :)

I'm testing out a new implementation of the search and hopefully it will solve the issue.

**Comment by viktorbenei** [comment]
Glad to hear, looking forward to test the new version! :)
