### ISSUE TITLE
Slack CLI Client not updating message window when I send message or a new message arrives

### ISSUE THREAD

**Issue by rakesh-roshan** [erroneousboat/slack-term#72]
WHen I press enter to send message, I do not see anything in message window. When I change channel and come back to channel, I can see that message.

**Comment by rakesh-roshan** [comment]
I tried in linux too, it is not updating there.

**Comment by erroneousboat** [comment]
Is it possible that your system is blocking connections over websockets?

**Comment by glycerine** [comment]
Same issue for me. It looks like the client is only refreshing when moving away from the channel and then returning it.  Is the client supposed to poll every so often, or get some kind of real time notice?

**Comment by glycerine** [comment]
> Is it possible that your system is blocking connections over websockets?

Since the normal gui slack client works fine, and slack-term refreshes fine upon changing channels, I don't think that's the issue.

**Comment by glycerine** [comment]
I wonder if something changed on the Slack side, since https://github.com/1egoman/slick seems to have the same problem.

**Comment by erroneousboat** [comment]
@glycerine At the time you were reporting this issue there were connectivity issues with slack

https://status.slack.com/2018-01/d8cf1517de9ecfa8
https://twitter.com/SlackHQ/status/950812653496053760

**Comment by glycerine** [comment]
That wouldn't explain the asymmetry between the gui and the slack-term. I just retested now and the problem remains.

**Comment by rakesh-roshan** [comment]
I am still seeing this problem. Is there any way to open this cli tool in verbose mode or some location of log?

**Comment by erroneousboat** [comment]
@glycerine I'm sorry that you are having issues with slack-term, but I'm not able to reproduce your issue. Furthermore, I don't know how the gui receives and sends messages, so I don't know if both programs use the same methods for sending and receiving messages, but this is how slack-term does it:

slack-term uses https://github.com/nlopes/slack for communicating with the slack api. When you are changing channels it will use the [GetChannelHistory](https://api.slack.com/methods/channels.history) method, which is a REST call to `api.slack.com`. When you are receiving and sending messages it is using the [Real-Time Messaging protocol](https://godoc.org/github.com/nlopes/slack#Client.NewRTM) over websocket.

So, that leads me to believe there might be an issue with websocket on certain systems when using https://github.com/nlopes/slack I'll investigate this further whether this might be the problem.

**Comment by rakesh-roshan** [comment]
I think in my system, I found the problem. I was using company VPN while using this. So looks like company VPN blocks some websocket ports. After shutting down company VPN, it works fine.

**Comment by faguirre1** [comment]
I had the same issue at work, but this morning we changed our wifi router and it is working since then.
