### ISSUE TITLE
Fix documentation for colors and unify format

### ISSUE THREAD

**Issue by adius** [erroneousboat/slack-term#75]
1. The color `red` is not listed in the table.
2. For the `channel` and `message` sections you have to use the `fg-` and `bg-` prefixes to make it work

Also you should unify the interface for setting colors. I.e. use the prefixes for `view` as well:

```json
"view": {
  "fg": "white",
  "bg": "default",
  "border": "fg-magenta,bg-cyan",
  "par": "fg-red,bg-white"
}
```

**Comment by erroneousboat** [comment]
A lot of this has to do with termui and how it handles colors, I've updated the documentation and will add a full example. I will leave the rest as is.
