### ISSUE TITLE
Support for emojis

### ISSUE THREAD

**Issue by adius** [erroneousboat/slack-term#76]
`:slightly_smiling_face:` => :slightly_smiling_face:

**Comment by erroneousboat** [comment]
There is emoji support in slack-term however because of the following https://github.com/erroneousboat/slack-term/commit/0b10bbbc4c33003396d5528020ecea3e8717df0d, I've disabled it.

**Comment by adius** [comment]
I think there is a (new) flag in iTerm to fix this ([ ] support for unicode 9)

**Comment by erroneousboat** [comment]
I don't use iTerm so I have no way to test that, whether it is something with the terminal or one of the packages slack-term uses (termbox, termui). You can test it yourself by cloning the project and building it. I'll try to find a terminal emulator on linux that supports emoji.

**Comment by antekresic** [comment]
Go to Preferences->Profiles->Text, enable "Treat ambiguous-width characters as double-width." seems to fix the emoji issue for me. I'm running iTerm2 version: 3.1.5.beta.2

**Comment by espoelstra** [comment]
As of Ubuntu 18.04 (Gnome 3.26-3.28) emoji are supposedly supported "everywhere" in the UI.
