### ISSUE TITLE
Feature request: colorize the chat window

### ISSUE THREAD

**Issue by howardcochran** [erroneousboat/slack-term#79]
Chats would be much easier to follow if the the author name of each message were displayed in a unique, persistent color, and if the timestamp were displayed in a color other than the default text color.

Here is a random example of what I mean (from irssi):
https://i.stack.imgur.com/89nsP.png

Thanks!

**Comment by erroneousboat** [comment]
You can alter the color of the time, see the readme/wiki for that. I'll think about the unique color to name request.

**Comment by Zebrazilla** [comment]
I see there was some effort done to colorize names in the chat window but was it ever released?

**Comment by erroneousboat** [comment]
@Zebrazilla it will be available in the upcoming version, you can check it out in the branch `v0.4.1`, add `colorize` to `name` in the slack-term config file to get individualized name colors. e.g.:

```javascript
{
  "theme": {
    "message": "colorize,fg-bold"
  }
}
```

**Comment by YWFT** [comment]
I second this, but as of now any changes made to slack-term.json don't seem to take with regards to color, less It's just me  :)
