### ISSUE TITLE
How do I make the channel column wider?

### ISSUE THREAD

**Issue by nikolas** [erroneousboat/slack-term#82]
My slack-term looks like this:
![2018-02-01-105053_1011x662_scrot](https://user-images.githubusercontent.com/59292/35687861-cff03680-073d-11e8-9d1f-ebc68d9b7664.png)

How do I make the channel column wider, other than making the entire window wider?

**Comment by erroneousboat** [comment]
please refer to the readme

**Comment by nikolas** [comment]
thanks!
