### ISSUE TITLE
chat-up command crashes slack-term

### ISSUE THREAD

**Issue by nikolas** [erroneousboat/slack-term#83]
I'm not sure what this command is supposed to do, but using `C-b` or `C-u` in my slack-term causes this crash:

```
Captured a panic(value=runtime error: index out of range) when rendering Bufferer. Exit termui and clean terminal...
Print stack trace:

1: running [Created by termui.Init @ render.go:63]
    debug      stack.go:24   Stack(0xad50c0, 0xc420090010, 0x8b77be)
    termui     render.go:107 render.func1()
               panic.go:491  panic(0x819540, 0xb083e0)
    components chat.go:121   (*Chat).Buffer(0xc4203c62b0, 0, 0, 0, 0, 0)
    termui     render.go:124 render(0xc4203df400, 0x1, 0x1)
    termui     render.go:65  Init.func2()
```

I'm on Debian testing amd64, go version 1.9.3. Using the latest git version of slack-term.

**Comment by nikolas** [comment]
by the way, this crash doesn't occur on my system anymore. I'm able to scroll up and down without any trouble. i'm not away of any changes on my end - sorry i can't provide more info.

**Comment by erroneousboat** [comment]
It can be triggered in an empty chat view and scrolling up. A fix will be available in the upcoming version.
