### ISSUE TITLE
Print date between messages if they are from different days

### ISSUE THREAD

**Issue by antekresic** [erroneousboat/slack-term#84]
I made small change to my local build because I was missing the date limiters from Slack web client. 

My rough change looks like this:
![change screenshot](https://user-images.githubusercontent.com/1985166/36415053-ccac8122-1624-11e8-8400-b1c6896665bf.png)

If there is enough interest for this feature or we just agree that it would be nice to add, I can prepare a PR when I catch some time.

P.S.: awesome project! :)

**Comment by stevenklar** [comment]
Please do the pull request :-) :+1:

**Comment by nud3l** [comment]
Can you share your code?

**Comment by oliverseal** [comment]
Oh I didn't even see this issue before I posted #157 .
Neat.
