### ISSUE TITLE
Garbled text with ncurses 6.1-3 on Arch Linux

### ISSUE THREAD

**Issue by markhuge** [erroneousboat/slack-term#85]
Don't know that this is a slack-term problem, but just opening an issue in case anyone else runs into this.

Launching slack-term with the new ncurses 6.1-3 on Arch Linux, in any term or system console, displays garbled unicode characters. Downgrading to the prior version (6.0+20170902-3) resolves this issue for me:

`sudo pacman -U /var/cache/pacman/pkg/ncurses-6.0+20170902-3-x86_64.pkg.tar.xz`

**Comment by erroneousboat** [comment]
@markhuge Is this the same as #98?

**Comment by erroneousboat** [comment]
Duplicate of #98
