### ISSUE TITLE
Screen bug on xterm-256color

### ISSUE THREAD

**Issue by franklyshin** [erroneousboat/slack-term#87]
$TERM = "xterm-256color"

I don't know why, but slack-term fails to render on xterm-256color.
It works fine on rxvt-unicode-256color.

I have attached the screenshot of the symptom.

![2018-02-22-203714_576x1044_scrot](https://user-images.githubusercontent.com/8732646/36573768-8681d434-1810-11e8-85ef-75978fc2b0f9.png)

**Comment by belak** [comment]
Out of curiosity, what actual terminal are you using?

**Comment by dpgeekzero** [comment]
I'm seeing it with Gnome Terminal, xterm-termite would be great too.  :)

**Comment by nhumrich** [comment]
I'm seeing this with `Konsole` (kde-plasma's terminal)

**Comment by tonylambiris** [comment]
FYI I set an alias to slack-term in the interim:
```
> alias slack-term 
slack-term='TERM=xterm slack-term'
```

![screenshot-20180301220443-838x585](https://user-images.githubusercontent.com/14058972/36881572-ce04b628-1d9c-11e8-8ea1-9a27b7dccfe3.jpg)

Apologies for the redaction of chan info, #corporateamericalife

**Comment by tonylambiris** [comment]
As a follow-up, it appears like a fix has been identified.
https://github.com/nsf/termbox-go/issues/185

**Comment by hshin23** [comment]
@tonylambiris That seems to be a temporary work around -- and the use of `-` between the `boston` and `office` lol
@belak I'm using Terminator.

**Comment by erroneousboat** [comment]
Closing this to keep discussion on #98 

@tonylambiris thank you for the workaround, and identifying the termbox issue
