### ISSUE TITLE
Add mouse support

### ISSUE THREAD

**Issue by jpillora** [erroneousboat/slack-term#90]
Haven't looked into how it's implemented, however `htop` for example, supports mouse clicks to select a process. Would be nice if you could click channels, possibly click links and `open` them.

**Comment by EduardoRT** [comment]
A lot of the value of using the term is not having to use the mouse, imho. It would be nice to have for that one time you forget the keybinding but I don't think it's something important.

**Comment by erroneousboat** [comment]
At the moment my personal preference is not to implement this feature. Mainly it will mean that slack-term needs to support all different kind of clickable elements (channels, chat view, messages, etc.), as well as scrolling. It also will depend on the library that slack-term uses for the terminal interface, at the moment it uses termui, which for several reasons, I'd like to replace.

As clicking on links, the terminal emulator I use (gnome-terminal) is able to identify links and make them clickable. Another solution might be [urlview](https://github.com/sigpipe/urlview) which I use in combination with tmux: https://github.com/erroneousboat/dotfiles/blob/master/files/tmux/.tmux.conf#L116-L117

**Comment by floam** [comment]
> A lot of the value of using the term is not having to use the mouse, imho. It would be nice to have for that one time you forget the keybinding but I don't think it's something important.

Not just the "one" time you forgot a keybinding, but also before you've figured out the keybinding, or when the mouse would be genuinely more efficient, or also just any time you already have your hand on a mouse for some other reason and it could save time. Seriously, this could be a nice to have feature given that most of use are using terminal emulators. Of course you would never require a mouse to do anything.

**Comment by floam** [comment]
(Features like picking a comment to start a new thread, or adding reactions might come to mind. Scrolling events...)
