### ISSUE TITLE
Garbled interface (���)

### ISSUE THREAD

**Issue by dellamorte-dellamore** [erroneousboat/slack-term#98]
I got following message:
`
%p1%dGQ�����������������������������������������������������������������������������������������������������������������������������������������������������������������25h2018/03/02 11:53:46 json: cannot unmarshal string into Go struct field Config.theme of type config.Theme`

It worked correctly before but now i can't start it

**Comment by tobske** [comment]
I have a similar issue: I can still open slack-term but I see a lot of symbols just as @dellamorte-dellamore  does.

**Comment by yujikiriki** [comment]
+1, same issue with Arch + i3.

**Comment by dellamorte-dellamore** [comment]
I updated to latest version and issue still persists. I regenerated configuration file and i am able to open program now, but it is still messed up. @tobske i don't have go package installed at all.

**Comment by dtluna** [comment]
I get the same issue on Arch Linux by installing `slack-term` with `go get -u github.com/erroneousboat/slack-term`. 
I have installed the `go` package from official Arch repos:
```
$ pacman -Si go
Repository      : extra
Name            : go
Version         : 2:1.10-2
Description     : Core compiler tools for the Go programming language
Architecture    : x86_64
URL             : http://golang.org/
Licenses        : BSD
Groups          : None
Provides        : go-pie
Depends On      : None
Optional Deps   : None
Conflicts With  : go-pie
Replaces        : None
Download Size   : 67.17 MiB
Installed Size  : 330.41 MiB
Packager        : Bartlomiej Piotrowski <bpiotrowski@archlinux.org>
Build Date      : Sun 18 Feb 2018 02:39:44 PM +03
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

**Comment by AlphaWong** [comment]
Same case
![image](https://user-images.githubusercontent.com/5622516/37387626-1ec1e360-2798-11e8-8880-d99eff1d1dbd.png)

**Comment by erroneousboat** [comment]
Possible solutions/workarounds:
* https://github.com/gizak/termui/issues/20
* https://github.com/erroneousboat/slack-term/issues/94 (see comment of @Xide)

**Comment by dellamorte-dellamore** [comment]
I can run it from tmux without a problem, but not directly in Konsole.
