### ISSUE TITLE
Add token command or config inheritence

### ISSUE THREAD

**Issue by stevenklar** [erroneousboat/slack-term#99]
As a user of 5 different slack channels it is hard to share the same themes over all instances the whole time. It would be awesome to have some kind of config inheritence/merge or a simple command which overrides the config slack token.

E.g. new command
```slack-term -c slack-term.json -t AWESOME_SLACK_TOKEN_TEAM1
slack-term -c slack-term.json -t AWESOME_SLACK_TOKEN_TEAM2
slack-term -c slack-term.json -t AWESOME_SLACK_TOKEN_TEAM3
```

E. g. config inheritence/merge (which would make it more flexible)
```slack-term -c slack-term.json -c team1.json -c awesome.theme.json
slack-term -c slack-term.json -c team2.json -c material-theme.json
slack-term -c slack-term.json -c team3.json
```

So the configs get merged recursive so you can share the same colour settings or just override one/more settings.

I hope the explaination is clear. What do you think?

**Comment by erroneousboat** [comment]
Sorry but this is too specific for one use-case, and will create substantial complexity to the application, which can be solved (as far as I can see), by copying the configuration multiple times.
